name: deploy order

on:
  push:
    branches:
      - main

jobs:
  # job의 이름. 자유롭게 줄 수 있음
  build-and-deploy:
    #runner
    runs-on: ubuntu-latest
  # https://docs.github.com/ko/actions
    steps:
      - name: checkout github # 레포에서 코드 가져와서 러너에 깔아줘
        # uses: 명령어
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3

      # aws와 연결
      - name: aws configure
        # 약속된 명령어
        uses: aws-actions/configure-aws-credentials@v1
        with: # 추가 작업
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1

      # aws : cluster connextion
      - name: aws eks cluster update
      # 사용자가 직접 콘솔에 내리는 명령어는 uses가 아닌 run을 사용
        run: aws eks update-kubeconfig --region us-west-1 --name khs-cluster

      # ecr에 로그인 됨
      - name: aws ecr login
        uses: aws-actions/amazon-ecr-login@v1

      # 이미지 생성/push
      - name: image build and push docker image to ecr
        env:
          REGISTORY: 414901227428.dkr.ecr.us-west-1.amazonaws.com
          REPOSITORY: order-khs-backend
          IMAGE_TAG: latest
        run: | # yml파일에서 특정 명령어를 그룹화시킬 때 사용
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./Dockerfile
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG